config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get     'help'    => 'static_pages#help'
  get     'about'   => 'static_pages#about'
  get     'contact' => 'static_pages#contact'
  
  get     'signup'  => 'users#new'

  get     'login'   => 'sessions#new'
  post    'login'   => 'sessions#create'
  delete  'logout'  => 'sessions#destroy'

  resources :microposts
  resources :users
  

 

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
    belongs_to :user # принадлежность пользователю
    validates :content, length: { maximum: 140 }, # ограничение длины
    presence: true # проверка что не пусто
end

app/models/user.rb
class User < ActiveRecord::Base
    attr_accessor :remember_token

    #before_save {self.email = email.downcase}
    before_save {email.downcase!}
    validates :name, presence: true, length: { maximum: 50 }

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    #VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                      format: {with: VALID_EMAIL_REGEX},
                      uniqueness: {case_sensitive: false}
    
    has_secure_password
    validates :password, length: { minimum: 6 }

    # Возвращает дайджест для указанной строки.
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ?
                BCrypt::Engine::MIN_COST :
                BCrypt::Engine.cost
                BCrypt::Password.create(string, cost: cost)
    end

    # Возвращает случайный токен.
    def User.new_token
        SecureRandom.urlsafe_base64
    end

    # Запоминает пользователя в базе данных для использования в постоянных сеансах.
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end

    # Возвращает true, если указанный токен соответствует дайджесту.
    def authenticated?(remember_token)
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

    # Забывает пользователя
    def forget
        update_attribute(:remember_digest, nil)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  
  def hello
    render text: "hello, world!"
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]

  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.all
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url, notice: 'Micropost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:micropost).permit(:content, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Осуществить вход пользователя и переадресовать на страницу профиля.
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user
    else
      # Создать сообщение об ошибке.
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end 

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  #  debugger
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success]= "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
    # Возвращает полный заголовок на основе заголовка страницы.
    def full_title(page_title = '')
        base_title = "Ruby on Rails Tutorial Sample App"
        
        if page_title.empty?
            base_title
        else
            "#{page_title} | #{base_title}"
        end
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    # Осуществляет вход данного пользователя.
    def log_in(user)
        session[:user_id] = user.id
    end

# Возвращает пользователя, соответствующего токену в cookie.
    def current_user
        if (user_id = session[:user_id])
            @current_user ||= User.find_by(id: user_id)
        elsif (user_id = cookies.signed[:user_id])
            user = User.find_by(id: user_id)
            if user && user.authenticated?(cookies[:remember_token])
                log_in user
                @current_user = user
            end
        end
    end

    # Возвращает true, если пользователь зарегистрирован, иначе возвращает false.
    def logged_in?
        !current_user.nil?
    end

    # Осуществляет выход текущего пользователя.
    def log_out
        forget(current_user)
        session.delete(:user_id)
        @current_user = nil
    end

    # Запоминает пользователя в постоянном сеансе.
    def remember(user)
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
    end

    # Закрывает постоянный сеанс.
    def forget(user)
        user.forget
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    # Возвращает граватар для данного пользователя.
    def gravatar_for(user, options = { size: 80 })
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
        by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
    </small>
    <nav>
        <ul>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
            <li><a href="http://news.railstutorial.org/">News</a></li>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <%= link_to "sample app", root_path, id: "logo" %>
        <nav>
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Home", root_path %></li>
                <li><%= link_to "Help", help_path %></li>
                <% if logged_in? %>
                    <li><%= link_to "Users", '#' %></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Account <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><%= link_to "Profile", current_user %></li>
                            <li><%= link_to "Settings", '#' %></li> 
                            <li class="divider"></li>
                            <li>
                                <%= link_to "Log out", logout_path, method: "delete" %>
                            </li>
                        </ul>
                    </li>
                <% else %>
                    <li><%= link_to "Log in", login_path %></li>
                <% end %>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                          'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/microposts/_form.html.erb
<%= form_for(@micropost) do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @micropost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/microposts/edit.html.erb
<h1>Editing Micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Microposts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @microposts.each do |micropost| %>
      <tr>
        <td><%= micropost.content %></td>
        <td><%= micropost.user_id %></td>
        <td><%= link_to 'Show', micropost %></td>
        <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
        <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Micropost', new_micropost_path %>

app/views/microposts/new.html.erb
<h1>New Micropost</h1>

<%= render 'form' %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @micropost.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @micropost.user_id %>
</p>

<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            The form contains <%= pluralize(@user.errors.count, "error") %>.
        </div>
        <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/static_pages/about.html.erb
<h1>About</h1>
<p>
    The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
    Tutorial</em></a> is a
    <a href="http://www.railstutorial.org/book">book</a> and
    <a href="http://screencasts.railstutorial.org/">screencast series</a>
    to teach web development with
    <a href="http://rubyonrails.org/">Ruby on Rails</a>.
    This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>
<p>
    Contact the Ruby on Rails Tutorial about the sample app at the
    <a href="http://www.railstutorial.org/#contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<h1>Help</h1>
<p>
    Get help on the Ruby on Rails Tutorial at the
    <a href="http://www.railstutorial.org/#help">Rails Tutorial help
    section</a>.
    To get help on this sample app, see the
    <a href="http://www.railstutorial.org/book"><em>Ruby on Rails
    Tutorial</em> book</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
    <h1>Welcome to the Sample App</h1>
    <h2>
        This is the home page for the
        <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
        sample application.
    </h2>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>
<%= link_to image_tag("logo.svg", alt: "Rails logo"),
                            'http://rubyonrails.org/' %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user) do |f| %>
            <%= render 'shared/error_messages' %>

            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>

            <%= f.label :email %>
            <%= f.text_field :email, class: 'form-control' %>

            <%= f.label :password %>
            <%= f.text_field :password, class: 'form-control' %>

            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.text_field :password_confirmation, class: 'form-control' %>
            
            <%= f.submit "Create my account", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row"> 
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>